[package]
name = "survive"
version = "0.1.0"
authors = ["Skyler Lipthay <sl@skylerlipthay.com>"]
edition = "2018"

[dependencies]
bincode = "1.1"
byteorder = "1.3"
serde = "1.0"

[dev-dependencies]
serde_derive = "1.0"
